//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace emec {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    [System.Xml.Serialization.XmlRootAttribute("CurriculoEscolar", Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", IsNullable=false)]
    public partial class TCurriculoEscolar {
        
        private TInfCurriculoEscolar infCurriculoEscolarField;
        
        private SignatureType[] signatureField;
        
        /// <remarks/>
        public TInfCurriculoEscolar infCurriculoEscolar {
            get {
                return this.infCurriculoEscolarField;
            }
            set {
                this.infCurriculoEscolarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType[] Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TInfCurriculoEscolar {
        
        private string codigoCurriculoField;
        
        private System.DateTime dataCurriculoField;
        
        private uint minutosRelogioDaHoraAulaField;
        
        private string nomeParaAreasField;
        
        private object itemField;
        
        private TDadosIesEmissora iesEmissoraField;
        
        private TDadoEtiqueta[] infEtiquetasField;
        
        private TDadoArea[] infAreasField;
        
        private TUnidadeCurricular[] infEstruturaCurricularField;
        
        private TCategoriaAtividadeComplementar[] infEstruturaAtividadesComplementaresField;
        
        private object[] infCriteriosIntegralizacaoField;
        
        private TSegurancaCurriculo segurancaCurriculoField;
        
        private string informacoesAdicionaisField;
        
        private TVersao versaoField;
        
        private TAmb ambienteField;
        
        public TInfCurriculoEscolar() {
            this.ambienteField = TAmb.Produção;
        }
        
        /// <remarks/>
        public string CodigoCurriculo {
            get {
                return this.codigoCurriculoField;
            }
            set {
                this.codigoCurriculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataCurriculo {
            get {
                return this.dataCurriculoField;
            }
            set {
                this.dataCurriculoField = value;
            }
        }
        
        /// <remarks/>
        public uint MinutosRelogioDaHoraAula {
            get {
                return this.minutosRelogioDaHoraAulaField;
            }
            set {
                this.minutosRelogioDaHoraAulaField = value;
            }
        }
        
        /// <remarks/>
        public string NomeParaAreas {
            get {
                return this.nomeParaAreasField;
            }
            set {
                this.nomeParaAreasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DadosCurso", typeof(TDadosMinimoCurso))]
        [System.Xml.Serialization.XmlElementAttribute("DadosCursoNSF", typeof(TDadosMinimoCursoNSF))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public TDadosIesEmissora IesEmissora {
            get {
                return this.iesEmissoraField;
            }
            set {
                this.iesEmissoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Etiqueta", IsNullable=false)]
        public TDadoEtiqueta[] infEtiquetas {
            get {
                return this.infEtiquetasField;
            }
            set {
                this.infEtiquetasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Area", IsNullable=false)]
        public TDadoArea[] infAreas {
            get {
                return this.infAreasField;
            }
            set {
                this.infAreasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UnidadeCurricular", IsNullable=false)]
        public TUnidadeCurricular[] infEstruturaCurricular {
            get {
                return this.infEstruturaCurricularField;
            }
            set {
                this.infEstruturaCurricularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Categoria", IsNullable=false)]
        public TCategoriaAtividadeComplementar[] infEstruturaAtividadesComplementares {
            get {
                return this.infEstruturaAtividadesComplementaresField;
            }
            set {
                this.infEstruturaAtividadesComplementaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CriterioIntegralizacaoExpressao", typeof(TCriterioIntegralizacaoExpressao), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CriterioIntegralizacaoRotulos", typeof(TCriterioIntegralizacaoRotulos), IsNullable=false)]
        public object[] infCriteriosIntegralizacao {
            get {
                return this.infCriteriosIntegralizacaoField;
            }
            set {
                this.infCriteriosIntegralizacaoField = value;
            }
        }
        
        /// <remarks/>
        public TSegurancaCurriculo SegurancaCurriculo {
            get {
                return this.segurancaCurriculoField;
            }
            set {
                this.segurancaCurriculoField = value;
            }
        }
        
        /// <remarks/>
        public string InformacoesAdicionais {
            get {
                return this.informacoesAdicionaisField;
            }
            set {
                this.informacoesAdicionaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TVersao versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TAmb.Produção)]
        public TAmb ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TDadosMinimoCurso {
        
        private string nomeCursoField;
        
        private object itemField;
        
        private THabilitacao[] habilitacaoField;
        
        private TAtoRegulatorioComOuSemEMEC autorizacaoField;
        
        private TAtoRegulatorioComOuSemEMEC reconhecimentoField;
        
        private TAtoRegulatorioComOuSemEMEC renovacaoReconhecimentoField;
        
        /// <remarks/>
        public string NomeCurso {
            get {
                return this.nomeCursoField;
            }
            set {
                this.nomeCursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodigoCursoEMEC", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("SemCodigoCursoEMEC", typeof(TInformacoesTramitacaoEMEC))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Habilitacao")]
        public THabilitacao[] Habilitacao {
            get {
                return this.habilitacaoField;
            }
            set {
                this.habilitacaoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC Autorizacao {
            get {
                return this.autorizacaoField;
            }
            set {
                this.autorizacaoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC Reconhecimento {
            get {
                return this.reconhecimentoField;
            }
            set {
                this.reconhecimentoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC RenovacaoReconhecimento {
            get {
                return this.renovacaoReconhecimentoField;
            }
            set {
                this.renovacaoReconhecimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TInformacoesTramitacaoEMEC {
        
        private uint numeroProcessoField;
        
        private string tipoProcessoField;
        
        private System.DateTime dataCadastroField;
        
        private System.DateTime dataProtocoloField;
        
        /// <remarks/>
        public uint NumeroProcesso {
            get {
                return this.numeroProcessoField;
            }
            set {
                this.numeroProcessoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoProcesso {
            get {
                return this.tipoProcessoField;
            }
            set {
                this.tipoProcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                this.dataCadastroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataProtocolo {
            get {
                return this.dataProtocoloField;
            }
            set {
                this.dataProtocoloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Object", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class ObjectType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string idField;
        
        private string mimeTypeField;
        
        private string encodingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SPKIData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SPKIDataType {
        
        private byte[][] sPKISexpField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType="base64Binary")]
        public byte[][] SPKISexp {
            get {
                return this.sPKISexpField;
            }
            set {
                this.sPKISexpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("PGPData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class PGPDataType {
        
        private object[] itemsField;
        
        private ItemsChoiceType3[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType3[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType3 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        PGPKeyID,
        
        /// <remarks/>
        PGPKeyPacket,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType {
        
        private string x509IssuerNameField;
        
        private string x509SerialNumberField;
        
        /// <remarks/>
        public string X509IssuerName {
            get {
                return this.x509IssuerNameField;
            }
            set {
                this.x509IssuerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string X509SerialNumber {
            get {
                return this.x509SerialNumberField;
            }
            set {
                this.x509SerialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class X509DataType {
        
        private object[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType))]
        [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        X509CRL,
        
        /// <remarks/>
        X509Certificate,
        
        /// <remarks/>
        X509IssuerSerial,
        
        /// <remarks/>
        X509SKI,
        
        /// <remarks/>
        X509SubjectName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class RetrievalMethodType {
        
        private TransformType[] transformsField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Transform", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class TransformType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class RSAKeyValueType {
        
        private byte[] modulusField;
        
        private byte[] exponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Modulus {
            get {
                return this.modulusField;
            }
            set {
                this.modulusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Exponent {
            get {
                return this.exponentField;
            }
            set {
                this.exponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class DSAKeyValueType {
        
        private byte[] pField;
        
        private byte[] qField;
        
        private byte[] gField;
        
        private byte[] yField;
        
        private byte[] jField;
        
        private byte[] seedField;
        
        private byte[] pgenCounterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PgenCounter {
            get {
                return this.pgenCounterField;
            }
            set {
                this.pgenCounterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("KeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class KeyValueType {
        
        private object itemField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("KeyInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class KeyInfoType {
        
        private object[] itemsField;
        
        private ItemsChoiceType4[] itemsElementNameField;
        
        private string[] textField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType))]
        [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType))]
        [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType))]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType4[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType4 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        KeyName,
        
        /// <remarks/>
        KeyValue,
        
        /// <remarks/>
        MgmtData,
        
        /// <remarks/>
        PGPData,
        
        /// <remarks/>
        RetrievalMethod,
        
        /// <remarks/>
        SPKIData,
        
        /// <remarks/>
        X509Data,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureValueType {
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("DigestMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class DigestMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class ReferenceType {
        
        private TransformType[] transformsField;
        
        private DigestMethodType digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureMethodType {
        
        private string hMACOutputLengthField;
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string HMACOutputLength {
            get {
                return this.hMACOutputLengthField;
            }
            set {
                this.hMACOutputLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class CanonicalizationMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignedInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignedInfoType {
        
        private CanonicalizationMethodType canonicalizationMethodField;
        
        private SignatureMethodType signatureMethodField;
        
        private ReferenceType[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        public CanonicalizationMethodType CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SignatureMethodType SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ReferenceType[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureType {
        
        private SignedInfoType signedInfoField;
        
        private SignatureValueType signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private ObjectType[] objectField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        public SignatureValueType SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object")]
        public ObjectType[] Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TSegurancaCurriculo {
        
        private string codigoValidacaoField;
        
        /// <remarks/>
        public string CodigoValidacao {
            get {
                return this.codigoValidacaoField;
            }
            set {
                this.codigoValidacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TCodigos {
        
        private string[] codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Codigo")]
        public string[] Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TExpressao {
        
        private TCodigos itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Soma")]
        public TCodigos Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TCriterioIntegralizacaoExpressao {
        
        private string codigoField;
        
        private TExpressao expressaoField;
        
        private TCriterioLimitesCargas cargasHorariasCriterioField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public TExpressao Expressao {
            get {
                return this.expressaoField;
            }
            set {
                this.expressaoField = value;
            }
        }
        
        /// <remarks/>
        public TCriterioLimitesCargas CargasHorariasCriterio {
            get {
                return this.cargasHorariasCriterioField;
            }
            set {
                this.cargasHorariasCriterioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TCriterioLimitesCargas {
        
        private decimal[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CargaHorariaMaxima", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("CargaHorariaMinima", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("CargaHorariaParaTotal", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public decimal[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        CargaHorariaMaxima,
        
        /// <remarks/>
        CargaHorariaMinima,
        
        /// <remarks/>
        CargaHorariaParaTotal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TCriterioIntegralizacaoRotulos {
        
        private string codigoField;
        
        private TTipoUnidadeCurricular unidadeCurricularField;
        
        private bool unidadeCurricularFieldSpecified;
        
        private string[] etiquetaField;
        
        private TCriterioLimitesCargas cargasHorariasCriterioField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public TTipoUnidadeCurricular UnidadeCurricular {
            get {
                return this.unidadeCurricularField;
            }
            set {
                this.unidadeCurricularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnidadeCurricularSpecified {
            get {
                return this.unidadeCurricularFieldSpecified;
            }
            set {
                this.unidadeCurricularFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Etiqueta")]
        public string[] Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
        
        /// <remarks/>
        public TCriterioLimitesCargas CargasHorariasCriterio {
            get {
                return this.cargasHorariasCriterioField;
            }
            set {
                this.cargasHorariasCriterioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public enum TTipoUnidadeCurricular {
        
        /// <remarks/>
        Disciplina,
        
        /// <remarks/>
        Módulo,
        
        /// <remarks/>
        Atividade,
        
        /// <remarks/>
        Estágio,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Trabalho de Conclusão de Curso")]
        TrabalhodeConclusãodeCurso,
        
        /// <remarks/>
        Monografia,
        
        /// <remarks/>
        Artigo,
        
        /// <remarks/>
        Projeto,
        
        /// <remarks/>
        Produto,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Atividade Complementar")]
        AtividadeComplementar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Atividade de Extensão")]
        AtividadedeExtensão,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TAtividadeComplementar {
        
        private string codigoField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private decimal limiteCargaHorariaEmHoraRelogioField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal LimiteCargaHorariaEmHoraRelogio {
            get {
                return this.limiteCargaHorariaEmHoraRelogioField;
            }
            set {
                this.limiteCargaHorariaEmHoraRelogioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TCategoriaAtividadeComplementar {
        
        private string codigoField;
        
        private string nomeField;
        
        private decimal limiteCargaHorariaEmHoraRelogioField;
        
        private bool limiteCargaHorariaEmHoraRelogioFieldSpecified;
        
        private TAtividadeComplementar[] atividadesField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public decimal LimiteCargaHorariaEmHoraRelogio {
            get {
                return this.limiteCargaHorariaEmHoraRelogioField;
            }
            set {
                this.limiteCargaHorariaEmHoraRelogioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LimiteCargaHorariaEmHoraRelogioSpecified {
            get {
                return this.limiteCargaHorariaEmHoraRelogioFieldSpecified;
            }
            set {
                this.limiteCargaHorariaEmHoraRelogioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Atividade", IsNullable=false)]
        public TAtividadeComplementar[] Atividades {
            get {
                return this.atividadesField;
            }
            set {
                this.atividadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TCodigoArea {
        
        private string codigoField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TAreas {
        
        private TCodigoArea[] areaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Area")]
        public TCodigoArea[] Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TEtiqueta {
        
        private string codigoField;
        
        private uint cargaHorariaEmHoraAulaField;
        
        private bool cargaHorariaEmHoraAulaFieldSpecified;
        
        private decimal cargaHorariaEmHoraRelogioField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public uint CargaHorariaEmHoraAula {
            get {
                return this.cargaHorariaEmHoraAulaField;
            }
            set {
                this.cargaHorariaEmHoraAulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CargaHorariaEmHoraAulaSpecified {
            get {
                return this.cargaHorariaEmHoraAulaFieldSpecified;
            }
            set {
                this.cargaHorariaEmHoraAulaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CargaHorariaEmHoraRelogio {
            get {
                return this.cargaHorariaEmHoraRelogioField;
            }
            set {
                this.cargaHorariaEmHoraRelogioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TEquivalenciaUnidadesCurriculares {
        
        private TEquivalenciaUnidadesCurricularesUnidadesCurricularesEquivalente[] unidadesCurricularesEquivalenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnidadesCurricularesEquivalente")]
        public TEquivalenciaUnidadesCurricularesUnidadesCurricularesEquivalente[] UnidadesCurricularesEquivalente {
            get {
                return this.unidadesCurricularesEquivalenteField;
            }
            set {
                this.unidadesCurricularesEquivalenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TEquivalenciaUnidadesCurricularesUnidadesCurricularesEquivalente {
        
        private string[] codigoUnidadeEquivalenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodigoUnidadeEquivalente")]
        public string[] CodigoUnidadeEquivalente {
            get {
                return this.codigoUnidadeEquivalenteField;
            }
            set {
                this.codigoUnidadeEquivalenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TEmenta {
        
        private string[] itemEmentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemEmenta")]
        public string[] ItemEmenta {
            get {
                return this.itemEmentaField;
            }
            set {
                this.itemEmentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TUnidadeCurricular {
        
        private TTipoUnidadeCurricular tipoField;
        
        private string codigoField;
        
        private string nomeField;
        
        private uint cargaHorariaEmHoraAulaField;
        
        private bool cargaHorariaEmHoraAulaFieldSpecified;
        
        private decimal cargaHorariaEmHoraRelogioField;
        
        private TEmenta ementaField;
        
        private string faseField;
        
        private TEquivalenciaUnidadesCurriculares equivalenciasField;
        
        private string[] preRequisitosField;
        
        private TEtiqueta[] etiquetasField;
        
        private TAreas areasField;
        
        /// <remarks/>
        public TTipoUnidadeCurricular Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public uint CargaHorariaEmHoraAula {
            get {
                return this.cargaHorariaEmHoraAulaField;
            }
            set {
                this.cargaHorariaEmHoraAulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CargaHorariaEmHoraAulaSpecified {
            get {
                return this.cargaHorariaEmHoraAulaFieldSpecified;
            }
            set {
                this.cargaHorariaEmHoraAulaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CargaHorariaEmHoraRelogio {
            get {
                return this.cargaHorariaEmHoraRelogioField;
            }
            set {
                this.cargaHorariaEmHoraRelogioField = value;
            }
        }
        
        /// <remarks/>
        public TEmenta Ementa {
            get {
                return this.ementaField;
            }
            set {
                this.ementaField = value;
            }
        }
        
        /// <remarks/>
        public string Fase {
            get {
                return this.faseField;
            }
            set {
                this.faseField = value;
            }
        }
        
        /// <remarks/>
        public TEquivalenciaUnidadesCurriculares Equivalencias {
            get {
                return this.equivalenciasField;
            }
            set {
                this.equivalenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CodigoDependencia", IsNullable=false)]
        public string[] PreRequisitos {
            get {
                return this.preRequisitosField;
            }
            set {
                this.preRequisitosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Etiqueta", IsNullable=false)]
        public TEtiqueta[] Etiquetas {
            get {
                return this.etiquetasField;
            }
            set {
                this.etiquetasField = value;
            }
        }
        
        /// <remarks/>
        public TAreas Areas {
            get {
                return this.areasField;
            }
            set {
                this.areasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TDadoArea {
        
        private string[] codigoField;
        
        private string[] nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Codigo")]
        public string[] Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Nome")]
        public string[] Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TDadoEtiqueta {
        
        private string codigoField;
        
        private string nomeField;
        
        private TSimNao aplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculoField;
        
        private bool aplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculoFieldSpecified;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public TSimNao AplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculo {
            get {
                return this.aplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculoField;
            }
            set {
                this.aplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculoSpecified {
            get {
                return this.aplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculoFieldSpecified;
            }
            set {
                this.aplicadoAutomaticamenteUnidadesNaoPertencentesAoCurriculoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public enum TSimNao {
        
        /// <remarks/>
        Sim,
        
        /// <remarks/>
        Não,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TEndereco {
        
        private string logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string codigoMunicipioField;
        
        private string nomeMunicipioField;
        
        private TUf ufField;
        
        private string nomeMunicipioEstrangeiroField;
        
        private string cEPField;
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMunicipio {
            get {
                return this.nomeMunicipioField;
            }
            set {
                this.nomeMunicipioField = value;
            }
        }
        
        /// <remarks/>
        public TUf UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMunicipioEstrangeiro {
            get {
                return this.nomeMunicipioEstrangeiroField;
            }
            set {
                this.nomeMunicipioEstrangeiroField = value;
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public enum TUf {
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AP,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        DF,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        GO,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        RJ,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RR,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        TO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TDadosIesEmissora {
        
        private string nomeField;
        
        private uint codigoMECField;
        
        private string cNPJField;
        
        private TEndereco enderecoField;
        
        private TAtoRegulatorioComOuSemEMEC credenciamentoField;
        
        private TAtoRegulatorioComOuSemEMEC recredenciamentoField;
        
        private TAtoRegulatorioComOuSemEMEC renovacaoDeRecredenciamentoField;
        
        private TDadosIesEmissoraMantenedora mantenedoraField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public uint CodigoMEC {
            get {
                return this.codigoMECField;
            }
            set {
                this.codigoMECField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public TEndereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC Credenciamento {
            get {
                return this.credenciamentoField;
            }
            set {
                this.credenciamentoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC Recredenciamento {
            get {
                return this.recredenciamentoField;
            }
            set {
                this.recredenciamentoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC RenovacaoDeRecredenciamento {
            get {
                return this.renovacaoDeRecredenciamentoField;
            }
            set {
                this.renovacaoDeRecredenciamentoField = value;
            }
        }
        
        /// <remarks/>
        public TDadosIesEmissoraMantenedora Mantenedora {
            get {
                return this.mantenedoraField;
            }
            set {
                this.mantenedoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TAtoRegulatorioComOuSemEMEC {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("DataPublicacao", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("InformacoesTramitacaoEMEC", typeof(TInformacoesTramitacaoEMEC))]
        [System.Xml.Serialization.XmlElementAttribute("Numero", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NumeroDOU", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("PaginaPublicacao", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("SecaoPublicacao", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("Tipo", typeof(TTipoAtoComAtoProprio))]
        [System.Xml.Serialization.XmlElementAttribute("VeiculoPublicacao", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public enum TTipoAtoComAtoProprio {
        
        /// <remarks/>
        Parecer,
        
        /// <remarks/>
        Resolução,
        
        /// <remarks/>
        Decreto,
        
        /// <remarks/>
        Portaria,
        
        /// <remarks/>
        Deliberação,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Lei Federal")]
        LeiFederal,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Lei Estadual")]
        LeiEstadual,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Lei Municipal")]
        LeiMunicipal,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ato Próprio")]
        AtoPróprio,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Data,
        
        /// <remarks/>
        DataPublicacao,
        
        /// <remarks/>
        InformacoesTramitacaoEMEC,
        
        /// <remarks/>
        Numero,
        
        /// <remarks/>
        NumeroDOU,
        
        /// <remarks/>
        PaginaPublicacao,
        
        /// <remarks/>
        SecaoPublicacao,
        
        /// <remarks/>
        Tipo,
        
        /// <remarks/>
        VeiculoPublicacao,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TDadosIesEmissoraMantenedora {
        
        private string razaoSocialField;
        
        private string cNPJField;
        
        private TEndereco enderecoField;
        
        /// <remarks/>
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public TEndereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class TDadosMinimoCursoNSF {
        
        private string nomeCursoField;
        
        private object itemField;
        
        private THabilitacao[] habilitacaoField;
        
        private TAtoRegulatorioComOuSemEMEC autorizacaoField;
        
        private TAtoRegulatorioComOuSemEMEC reconhecimentoField;
        
        private TAtoRegulatorioComOuSemEMEC renovacaoReconhecimentoField;
        
        /// <remarks/>
        public string NomeCurso {
            get {
                return this.nomeCursoField;
            }
            set {
                this.nomeCursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodigoCursoEMEC", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("SemCodigoCursoEMEC", typeof(TInformacoesTramitacaoEMEC))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Habilitacao")]
        public THabilitacao[] Habilitacao {
            get {
                return this.habilitacaoField;
            }
            set {
                this.habilitacaoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC Autorizacao {
            get {
                return this.autorizacaoField;
            }
            set {
                this.autorizacaoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC Reconhecimento {
            get {
                return this.reconhecimentoField;
            }
            set {
                this.reconhecimentoField = value;
            }
        }
        
        /// <remarks/>
        public TAtoRegulatorioComOuSemEMEC RenovacaoReconhecimento {
            get {
                return this.renovacaoReconhecimentoField;
            }
            set {
                this.renovacaoReconhecimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public partial class THabilitacao {
        
        private string nomeHabilitacaoField;
        
        private System.DateTime dataHabilitacaoField;
        
        /// <remarks/>
        public string NomeHabilitacao {
            get {
                return this.nomeHabilitacaoField;
            }
            set {
                this.nomeHabilitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataHabilitacao {
            get {
                return this.dataHabilitacaoField;
            }
            set {
                this.dataHabilitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public enum TVersao {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.05")]
        Item105,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://portal.mec.gov.br/diplomadigital/arquivos-em-xsd")]
    public enum TAmb {
        
        /// <remarks/>
        Produção,
        
        /// <remarks/>
        Homologação,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Transforms", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class TransformsType {
        
        private TransformType[] transformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transform")]
        public TransformType[] Transform {
            get {
                return this.transformField;
            }
            set {
                this.transformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class ManifestType {
        
        private ReferenceType[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ReferenceType[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureProperties", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignaturePropertiesType {
        
        private SignaturePropertyType[] signaturePropertyField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SignatureProperty")]
        public SignaturePropertyType[] SignatureProperty {
            get {
                return this.signaturePropertyField;
            }
            set {
                this.signaturePropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureProperty", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignaturePropertyType {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string[] textField;
        
        private string targetField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
